### ISSUE TITLE
Feature suggestion: implicitly convert stderr to a String

### ISSUE THREAD

**Issue by n-eq** [tux3/armerge#4]
Hello,

In `MergeError::ExternalToolError`, `stderr` contain the error logs of the external tool. However, currently it's a `Vec<u8>`. For cases when there is an error it would be much more helpful for debugging to directly return the error as a string, using `String::from_utf8`.

Does this sound interesting to you? I can create a PR unless you want to work on it.

Thanks!

**Comment by tux3** [comment]
Hello, thanks for the suggestion, I think that's a good ergonomics improvement

I whipped up a branch quickly, let me know if that matches what you expected. I'm using from_utf8_lossy to avoid the failable case, but in practice this is for display, I don't think anyone will reasonably want to parse non-utf8 data from stdout/stderr

It's an API break, so requires a 2.0, but that's fine.

**Comment by n-eq** [comment]
Thanks for the effort, I just reviewed your PR.
